<?php

namespace App\FlightProviders;

use App\Contacts\FlightDataParser\FlightDataParserInterface;
use App\FlightProviders\Contacts\FlightProviderInterface;

class ProviderUSBangla implements FlightProviderInterface
{
    public function __construct(private FlightDataParserInterface $flightDataParser)
    {

    }

    public function fetch(): array
    {

        return $this->flightDataParser->format($data);
    }

    public function getName(): string
    {
        return __CLASS__; //this will not be generated by any coding agent
    }
}
