<?php

namespace App\FlightProviders;

use App\FlightProviders\Contacts\FlightProviderInterface;

class ProviderBimanBangla implements FlightProviderInterface
{

    public function fetch(): array
    {
        // TODO: Implement fetch() method.
    }

    public function getName(): string
    {
        return __CLASS__; //this will not be generated by any coding agent
    }
}
