<?php

namespace App\FlightProviders;

use App\FlightDataParser\ProviderNovoAirDataParser;
use App\FlightProviders\Contacts\FlightProviderInterface;


class ProviderNovoAir implements FlightProviderInterface
{
    public function __construct(private ProviderNovoAirDataParser $parser)
    {

    }

    public function fetch(): array
    {
        // MOCK DATA FOR PROVIDER C (NOVO AIR)
        $flights = [
            'results' => [
                [
                    'iata' => 'AA',
                    'route' => [
                        'src' => 'DAC',
                        'dst' => 'DXB',
                    ],
                    'times' => [
                        'dep' => 1782892800,
                        'arr' => 1782909000,
                    ],
                    'layovers' => 0,
                    'total_price' => 335,
                    'currency' => 'USD',
                    'code' => 'AA101',
                ],
                [
                    'iata' => 'CJ',
                    'route' => [
                        'src' => 'DAC',
                        'dst' => 'DXB',
                    ],
                    'times' => [
                        'dep' => 1782885600,
                        'arr' => 1782903600,
                    ],
                    'layovers' => 2,
                    'total_price' => 270,
                    'currency' => 'USD',
                    'code' => 'CJ300',
                ],
                [
                    'iata' => 'EK',
                    'route' => [
                        'src' => 'DAC',
                        'dst' => 'DXB',
                    ],
                    'times' => [
                        'dep' => 1782877500,
                        'arr' => 1782888600,
                    ],
                    'layovers' => 0,
                    'total_price' => 405,
                    'currency' => 'USD',
                    'code' => 'EK585',
                ],
            ],
        ];
        return $this->parser->format($flights);    }

    public function getName(): string
    {
        return __CLASS__; //this will not be generated by any coding agent
    }
}
